import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='main-section'>
        <section className='first-main'>
          <h1 aria-label='main page header'>Услуги с 3Д принтер!</h1>
        </section>
        <article>
          <h1 className='the-heading'>Услуги с 3D принтер</h1>
        </article>
      </section>
    </>
  )
}
