import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='main-section'>
        <article>
          <Image
            src='/images/shield-cell.jpg'
            alt='Prop image'
            width={300}
            height={300}
          />
        </article>
        <article>
          <h1 className='the-heading'>Услуги с 3D принтер</h1>
        </article>
      </section>
    </>
  )
}
